"""Remove score column from Patrol model

Revision ID: 272ca3677305
Revises: 598bb1493cc9
Create Date: 2024-07-18 21:41:17.637746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272ca3677305'
down_revision = '598bb1493cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrol', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
