"""Add discovered_magazines to Family

Revision ID: bd1e8a10eee8
Revises: 2fe71396ce1c
Create Date: 2024-07-16 22:55:16.913462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1e8a10eee8'
down_revision = '2fe71396ce1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discovered_magazines', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('discovered_magazines')

    # ### end Alembic commands ###
