"""Add assigned_magazines to Family

Revision ID: e16f10a1d338
Revises: bd1e8a10eee8
Create Date: 2024-07-16 23:49:37.969962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16f10a1d338'
down_revision = 'bd1e8a10eee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_magazines', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('assigned_magazines')

    # ### end Alembic commands ###
