INSERT INTO Family (id, name, magazine_list, route, meeting_place) VALUES
(1, 'hizop', 'a', 'a', 'Pomnik Polskiej Dywizji Pancernej ul. Przyrynek 2'),
(2, 'hortensja', 'b', 'a', 'Zdrój Królewski w Warszawie (ul. Zakroczymska/ul. Wenedów)'),
(3, 'jabłoń', 'c', 'a', 'Wieża widokowa (bulwar Karskiego)'),
(4, 'jaśmin', 'd', 'a', 'Multimedialny Park Fontann skwer 1 Dywizji Pancernej WP'),
(5, 'jeżówka', 'e', 'a', 'Skwer Powstańców Styczniowych (kamień)'),
(6, 'kocimiętka', 'f', 'a', 'Muzeum Sportu i Turystyki w Warszawie (przed budynkiem)'),
(7, 'klon', 'a', 'a', 'Pomnik "Husarz Polski" (ul. Skazańców ul. Piotra Ściegiennego)'),
(8, 'koniczyna', 'b', 'a', 'Plac zabaw (ul. Cudnowska/ ul. Skazańców)'),
(9, 'konwalia', 'c', 'a', 'Plaża Żoliborz (okolica Bulwaru Zbigniewa Religi)'),
(10, 'krwawnica', 'd', 'a', 'Światłotrysk (Łacha Potocka)'),
(11, 'krwawnik', 'e', 'a', 'Ślizg (Bulwar Zbigniewa Religi)'),
(12, 'laurencja', 'f', 'a', 'Fort Legionów (przed budynkiem)- ul. Zakroczymska 12'),
(13, 'lilia', 'a', 'a', 'Tablica pamiątkowa - Płyta desantu na przyczółku żoliborskim (niedaleko Liceum Muzycznego na ul. Krasińskiego)'),
(14, 'lipa', 'b', 'a', 'Park Fosa i Stoki Cytadeli w Warszawie (przy stawie)'),
(15, 'magnolia', 'c', 'a', 'Mural Powstania Warszawskiego ul. Przyrynek 2'),
(16, 'mak', 'd', 'a', 'Pomnik Polskiej Dywizji Pancernej ul. Przyrynek 2'),
(17, 'malina', 'e', 'a', 'Zdrój Królewski w Warszawie (ul. Zakroczymska/ul. Wenedów)'),
(18, 'malwa', 'f', 'a', 'Wieża widokowa (bulwar Karskiego)'),
(19, 'melisa', 'a', 'a', 'Multimedialny Park Fontann skwer 1 Dywizji Pancernej WP'),
(20, 'mięta', 'b', 'a', 'Skwer Powstańców Styczniowych (kamień)'),
(21, 'mikołajek', 'c', 'a', 'Muzeum Sportu i Turystyki w Warszawie (przed budynkiem)'),
(22, 'mniszek', 'd', 'a', 'Pomnik "Husarz Polski" (ul. Skazańców ul. Piotra Ściegiennego)'),
(23, 'nawłoć', 'e', 'a', 'Plac zabaw (ul. Cudnowska/ ul. Skazańców)'),
(24, 'niezapominajka', 'f', 'a', 'Plaża Żoliborz (okolica Bulwaru Zbigniewa Religi)'),
(25, 'pierwiosnek', 'a', 'a', 'Światłotrysk (Łacha Potocka)'),
(26, 'pigwowiec', 'b', 'a', 'Ślizg (Bulwar Zbigniewa Religi)'),
(27, 'przegorzan', 'c', 'a', 'Fort Legionów (przed budynkiem)- ul. Zakroczymska 12'),
(28, 'pszczełnik', 'd', 'a', 'Tablica pamiątkowa - Płyta desantu na przyczółku żoliborskim (niedaleko Liceum Muzycznego na ul. Krasińskiego)'),
(29, 'rdest', 'e', 'a', 'Park Fosa i Stoki Cytadeli w Warszawie (przy stawie)'),
(30, 'robinia', 'f', 'a', 'Mural Powstania Warszawskiego ul. Przyrynek 2'),
(31, 'róża', 'a', 'a', 'Pomnik Polskiej Dywizji Pancernej ul. Przyrynek 2'),
(32, 'ruta', 'b', 'a', 'Zdrój Królewski w Warszawie (ul. Zakroczymska/ul. Wenedów)'),
(33, 'słonecznik', 'c', 'a', 'Wieża widokowa (bulwar Karskiego)'),
(34, 'stewia', 'd', 'a', 'Multimedialny Park Fontann skwer 1 Dywizji Pancernej WP'),
(35, 'śnieguliczka', 'e', 'a', 'Skwer Powstańców Styczniowych (kamień)'),
(36, 'tulipan', 'f', 'a', 'Muzeum Sportu i Turystyki w Warszawie (przed budynkiem)'),
(37, 'wiśnia', 'a', 'a', 'Pomnik "Husarz Polski" (ul. Skazańców ul. Piotra Ściegiennego)'),
(38, 'wrzos', 'b', 'a', 'Plac zabaw (ul. Cudnowska/ ul. Skazańców)'),
(39, 'żmijowiec', 'c', 'a', 'Plaża Żoliborz (okolica Bulwaru Zbigniewa Religi)'),
(40, 'żywokost', 'd', 'a', 'Światłotrysk (Łacha Potocka)'),
(41, 'aksamitka', 'e', 'b', 'Ślizg (Bulwar Zbigniewa Religi)'),
(42, 'aster', 'f', 'b', 'Fort Legionów (przed budynkiem)- ul. Zakroczymska 12'),
(43, 'berberys', 'a', 'b', 'Tablica pamiątkowa - Płyta desantu na przyczółku żoliborskim (niedaleko Liceum Muzycznego na ul. Krasińskiego)'),
(44, 'bugenwilla', 'b', 'b', 'Park Fosa i Stoki Cytadeli w Warszawie (przy stawie)'),
(45, 'chaber', 'c', 'b', 'Mural Powstania Warszawskiego ul. Przyrynek 2'),
(46, 'cynia', 'd', 'b', 'Pomnik Polskiej Dywizji Pancernej ul. Przyrynek 2'),
(47, 'cząber', 'e', 'b', 'Zdrój Królewski w Warszawie (ul. Zakroczymska/ul. Wenedów)'),
(48, 'czosnek', 'f', 'b', 'Wieża widokowa (bulwar Karskiego)'),
(49, 'dalia', 'a', 'b', 'Multimedialny Park Fontann skwer 1 Dywizji Pancernej WP'),
(50, 'dziwaczek', 'b', 'b', 'Skwer Powstańców Styczniowych (kamień)'),
(51, 'dzwonek', 'c', 'b', 'Muzeum Sportu i Turystyki w Warszawie (przed budynkiem)'),
(52, 'facelia', 'd', 'b', 'Pomnik "Husarz Polski" (ul. Skazańców ul. Piotra Ściegiennego)'),
(53, 'floks', 'e', 'b', 'Plac zabaw (ul. Cudnowska/ ul. Skazańców)'),
(54, 'gazania', 'f', 'b', 'Plaża Żoliborz (okolica Bulwaru Zbigniewa Religi)'),
(55, 'głóg', 'a', 'b', 'Światłotrysk (Łacha Potocka)'),
(56, 'gryka', 'b', 'b', 'Ślizg (Bulwar Zbigniewa Religi)'),
(57, 'żurawka', 'c', 'a', 'Fort Legionów (przed budynkiem)- ul. Zakroczymska 12'),
(58, 'żeniszek', 'd', 'a', 'Tablica pamiątkowa - Płyta desantu na przyczółku żoliborskim (niedaleko Liceum Muzycznego na ul. Krasińskiego)'),
(59, 'żeleźniak', 'a', 'a', 'Park Fosa i Stoki Cytadeli w Warszawie (przy stawie)');
